version: '3.8'
services:
  mongo_service:
    container_name: mongodb
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./.mongo-data:/data/db
    restart: 'always'
    ports:
        - '27017:27017'
    image: dannyben/alpine-mongo
    tty: true
networks:
  default:
    driver: bridge
